Repository ServiceNow/BrowserGym, pull requests merged in 2024-06, with the labels that each got.

#69 preprocess last obs (fix)
  experiments/src/browsergym/experiments/loop.py
Labels: bug

#75 Miniwob robust validation
  miniwob/src/browsergym/miniwob/base.py
  miniwob/tests/test_base.py
Labels: bug

#74 Python requirement >3.9
  core/pyproject.toml
Labels: bug

#70 Infeasible actions for WebArena
  core/src/browsergym/core/action/highlevel.py
  webarena/src/browsergym/webarena/task.py
  webarena/tests/test_infeasible.py
Labels: enhancement

#82 [Documentation] Building a new task
  .gitignore
  docs/Makefile
  docs/requirements.txt
  docs/src/api.rst
  docs/src/conf.py
  docs/src/core/action_space.rst
  docs/src/core/core.rst
  docs/src/core/observation_space.rst
  docs/src/environments/miniwob.rst
  docs/src/environments/webarena.rst
  docs/src/environments/workarena.rst
  docs/src/examples/create_custom_task.rst
  docs/src/examples/walkthrough.rst
  docs/src/index.rst
  docs/src/tutorials.rst
Labels: documentation
